name: flutter_komik
description: 'Necomic adalah aplikasi informasi komik yang dimana user bisa menjelajahi berbagai jenis komik.API yang digunakan untuk data komik aplikasi ini adalah menggunakan Jikan API.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.5
  shimmer: ^3.0.0
  intl: ^0.19.0
  readmore: ^3.0.0
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/icon.png'
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: '#ffffff' # You can use a color or image for the background
  adaptive_icon_foreground: 'assets/images/icon.png' # For adaptive icons on Android
  web:
    generate: true
    image_path: 'assets/images/icon.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/images/icon.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/icon.png'
