// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEiaqSsnr_vrrUyTEL4C7s5YoJ9IRcv5w',
    appId: '1:784107854327:web:72f495b83c73ff35c8f6f2',
    messagingSenderId: '784107854327',
    projectId: 'necomic',
    authDomain: 'necomic.firebaseapp.com',
    storageBucket: 'necomic.appspot.com',
    measurementId: 'G-S6W3QENWJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQux5xJX2SB5L8W96ua-fe2UrfLSvpCw',
    appId: '1:784107854327:android:ea6bb5304a1dd547c8f6f2',
    messagingSenderId: '784107854327',
    projectId: 'necomic',
    storageBucket: 'necomic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9WR14PetjmWi04fahzz9-qN08QGxXBYI',
    appId: '1:784107854327:ios:71c004a61b6a598ec8f6f2',
    messagingSenderId: '784107854327',
    projectId: 'necomic',
    storageBucket: 'necomic.appspot.com',
    iosBundleId: 'com.example.flutterKomik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9WR14PetjmWi04fahzz9-qN08QGxXBYI',
    appId: '1:784107854327:ios:71c004a61b6a598ec8f6f2',
    messagingSenderId: '784107854327',
    projectId: 'necomic',
    storageBucket: 'necomic.appspot.com',
    iosBundleId: 'com.example.flutterKomik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEiaqSsnr_vrrUyTEL4C7s5YoJ9IRcv5w',
    appId: '1:784107854327:web:2eb0ecf2bf7b5dc2c8f6f2',
    messagingSenderId: '784107854327',
    projectId: 'necomic',
    authDomain: 'necomic.firebaseapp.com',
    storageBucket: 'necomic.appspot.com',
    measurementId: 'G-NHXC8P3HGN',
  );
}
